Updated Hugo + Small Fixes
jolexa/hugo-lambda-function pull request #1
Opened 2016-11-25 18:54 UTC by abdel

* Updated Hugo to v0.17
* Added a `HUGO_VERSION` variable to easily update versions in the future
* Lambda function threw errors for missing `yaml` module, added `pyyaml` to `pip install`
* Changed go filename to `hugo.go` to avoid updating it for versions as well

2016-11-26 19:47 UTC, jolexa requested changes
Looks good to me, just a few comments to resolve. Thanks!

2016-11-26 19:47 UTC, jolexa commented on build-package.sh
> +wget https://raw.githubusercontent.com/abdel/hugo-lambda-function/master/main.py
It looks like this line snuck into the PR

2016-11-26 19:47 UTC, jolexa commented on build-package.sh
> +wget https://raw.githubusercontent.com/aws/aws-cli/develop/bin/aws \
It feels odd to me to pull in the "develop" branch of this file. How about the latest release? "1.11.21"

2016-11-27 01:49 UTC, abdel commented on build-package.sh
> +wget https://raw.githubusercontent.com/aws/aws-cli/develop/bin/aws \
I updated this to use the latest release instead. Seems like they were using develop as their main branch, and I just went for that one!

2016-11-29 22:07 UTC, jolexa commented on build-package.sh
> +wget https://raw.githubusercontent.com/aws/aws-cli/develop/bin/aws \
To be honest, I don't know the strategy. master is 61 commits ahead of 'develop' 😕

2016-11-29 22:07 UTC, merged